# Generated by Django 5.0.2 on 2024-03-08 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('game', '0014_gamevoucher_minimum_spend'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileavatar',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
            preserve_default=False,
        ),
    ]
