# Generated by Django 5.0.2 on 2024-03-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorder',
            name='order_id',
            field=models.UUIDField(blank=True, default='528e2c20f17a446a8281b9286595300d', editable=False, null=True),
        ),
    ]
