# Generated by Django 5.0.2 on 2024-03-04 11:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gameorder_buyer_alter_gameorder_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorder',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('645df354-4f3c-4f51-a3be-a42bf13b0acd'), editable=False),
        ),
    ]
