# Generated by Django 5.0.2 on 2024-03-04 11:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gameorder_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorder',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('c71bbf9a-2d7d-4acb-8378-cf61ebeb53ab'), editable=False),
        ),
    ]
