# Generated by Django 5.0.2 on 2024-03-04 11:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_gameorder_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorder',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('35e78b91-b4ea-4a05-967b-b6baa55aac11'), editable=False, unique=True),
        ),
    ]
