# Generated by Django 5.0.2 on 2024-03-04 11:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_gameorder_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorder',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
