# Generated by Django 5.0.2 on 2024-03-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_gameorder_pidx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorder',
            name='pidx',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
