# Generated by Django 5.0.2 on 2024-03-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_gameorder_pidx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='total_price',
        ),
    ]
