# Generated by Django 5.0.2 on 2024-03-07 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_wishlist_buyer_remove_wishlist_games_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedGame',
        ),
    ]
