# Generated by Django 5.0.2 on 2024-03-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_delete_featuredgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamevoucher',
            name='minimum_spend',
            field=models.FloatField(default=0),
        ),
    ]
