# Generated by Django 5.0.2 on 2024-03-08 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_gamevoucher_minimum_spend'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameorder',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
