# Generated by Django 5.0.2 on 2024-03-08 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_gameorder_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamereview',
            name='review_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
