# Generated by Django 5.0.2 on 2024-03-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_gamereview_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameorder',
            name='associated_order_id',
            field=models.UUIDField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
