# Generated by Django 5.0.2 on 2024-03-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_remove_gameorder_associated_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecode',
            name='associated_order_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
