# Generated by Django 5.0.2 on 2024-03-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_game_video_id_game_youtube_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='video_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='youtube_trailer',
        ),
        migrations.AddField(
            model_name='game',
            name='yt_trailer_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='YouTube trailer ID'),
        ),
    ]
