# Generated by Django 5.0.2 on 2024-03-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_remove_game_video_id_remove_game_youtube_trailer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steam_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Steam App ID'),
        ),
    ]
