# Generated by Django 5.0.2 on 2024-07-15 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_alter_game_steam_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.BooleanField()),
                ('adventure', models.BooleanField()),
                ('anime', models.BooleanField()),
                ('fps', models.BooleanField()),
                ('horror', models.BooleanField()),
                ('indie', models.BooleanField()),
                ('open_world', models.BooleanField()),
                ('racing', models.BooleanField()),
                ('rpg', models.BooleanField()),
                ('simulation', models.BooleanField()),
                ('sports', models.BooleanField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
