# Generated by Django 5.0.2 on 2024-08-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_gamegenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='long_description',
            field=models.TextField(blank=True, default='No description provided'),
        ),
    ]
