# Generated by Django 5.1.4 on 2024-12-12 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_game_long_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinSystemRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=250)),
                ('processor', models.CharField(max_length=500)),
                ('memory', models.CharField(max_length=250)),
                ('graphics', models.CharField(max_length=250)),
                ('storage', models.CharField(max_length=250)),
                ('additional_note', models.TextField(blank=True, max_length=1000)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedSystemRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=250)),
                ('processor', models.CharField(max_length=500)),
                ('memory', models.CharField(max_length=250)),
                ('graphics', models.CharField(max_length=250)),
                ('storage', models.CharField(max_length=250)),
                ('additional_note', models.TextField(blank=True, max_length=1000)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
