# Generated by Django 5.1.4 on 2024-12-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_minsystemrequirement_recommendedsystemrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewGameGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(blank=True, to='game.newgamegenre'),
        ),
    ]
