# Generated by Django 5.1.4 on 2024-12-17 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_game_developer_game_publisher_game_support_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameorder',
            name='voucher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gamevoucher'),
        ),
    ]
