# Generated by Django 5.1.4 on 2024-12-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_delete_gamegenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameorder',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Canceled'), (4, 'Expired'), (5, 'Failed')], default=1),
            preserve_default=False,
        ),
    ]
