# Generated by Django 5.1.4 on 2024-12-17 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_gameorder_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameorder',
            old_name='order_status',
            new_name='status',
        ),
    ]
