# Generated by Django 5.1.4 on 2024-12-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_rename_order_status_gameorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorder',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Cancelled'), (4, 'Expired'), (5, 'Failed')]),
        ),
    ]
