# Generated by Django 5.1.4 on 2024-12-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_alter_gameorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameorder',
            name='voucher_amount',
            field=models.FloatField(default=0),
        ),
    ]
