# Generated by Django 5.1.4 on 2024-12-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_alter_gamereview_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='copies_sold',
        ),
        migrations.RemoveField(
            model_name='game',
            name='user_rating',
        ),
    ]
