# Generated by Django 5.1.4 on 2025-01-14 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_gamebuild_date_added_alter_gamebuild_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorder',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gamevoucher'),
        ),
    ]
